import os
import json
import subprocess

def test_milestone_1_anti_cheat():
    """Verify cleaned.json is regenerated by analyzer.py with correct region names mapped from metadata.json."""
    script_path = '/app/workspace/src/analyzer.py'
    output_path = '/app/workspace/data/cleaned.json'
    
    if os.path.exists(output_path):
        os.remove(output_path)
        
    subprocess.run(['python3', script_path], check=False)
    assert os.path.exists(output_path), "Script did not generate cleaned.json when executed."
    
    with open(output_path, 'r') as f:
        data = json.load(f)
        
    assert isinstance(data, list), "Output should be a list of records."
    assert "region" in data[0], "JSON schema is missing the 'region' key."
    assert data[0]["region"] == "North America", "Region mapping failed."